image: gitpod/workspace-java-17

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    # - yaozheng.vscode-pde

workspaceLocation: "./kura/kura"

tasks:
  - init: |
      cd ../
      mvn -f target-platform/pom.xml clean install -B
      mvn -f kura/pom.xml clean install -Dmaven.test.skip=true
      mvn -f kura/pom.xml test-compile
